name: Generate Snake Animation

on:
  # Tự động chạy mỗi 12 giờ
  schedule:
    - cron: "0 */12 * * *"
  
  # Cho phép chạy thủ công
  workflow_dispatch:
  
  # Chạy khi push vào main
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    permissions:
      contents: write
    
    steps:
      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Son-Uchiha
          outputs: |
            dist/github-snake.svg?color_snake=#00C2FF&color_dots=#ebedf0,#c0e4ff,#7ab8ff,#338cff,#00C2FF
            dist/github-snake-dark.svg?color_snake=#ffffff&color_dots=#161b22,#003140,#006280,#0092c0,#00c2ff

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
